add support for Layout Management
HaikuArchives/WakeUp pull request #8
Opened 2020-01-08 01:35 UTC by Ra-V2

Fixes #7

2020-01-08 02:07 UTC, owenca commented
Setting fonts to 8 points doesn't look good:
![layout](https://user-images.githubusercontent.com/6434360/71944401-7fe87a00-3178-11ea-828d-36c657ca1946.png)

2020-01-08 02:10 UTC, owenca commented
Also, make the input box narrower and group it with "min" so that the gap between them is not too wide.

2020-01-08 10:01 UTC, owenca requested changes
When the user press the Start button, the timer is supposed to be displayed above the button, erasing the Test button and the sound file name. Hence you have to swap them dynamically.

2020-01-08 10:01 UTC, owenca commented on buzzwindow.cpp
> +										NULL, B_WILL_DRAW);
Merge them into one line.

2020-01-09 08:55 UTC, owenca requested changes
There are two problems now:
- The window shrinks in height when the timer is displayed.
- The widgets are not centered anymore.

2020-01-09 08:55 UTC, owenca commented on buzzwindow.cpp
> +	: BWindow(BRect(30, 30, 0, 0), "WakeUp v1.0", B_TITLED_WINDOW, B_NOT_RESIZABLE | B_NOT_ZOOMABLE | B_AUTO_UPDATE_SIZE_LIMITS)
Coding style.

2020-01-10 01:46 UTC, owenca requested changes

2020-01-10 01:46 UTC, owenca commented on buzzwindow.cpp
> +#include <GroupLayoutBuilder.h>
You don't need these two lines.

2020-01-10 01:46 UTC, owenca commented on buzzwindow.cpp
> +	: BWindow(BRect(30, 30, 0, 0), "WakeUp v1.0",
The `:` should be on its own line. Please refer to [Haiku Coding Guidelines](https://www.haiku-os.org/development/coding-guidelines/).

2020-01-10 01:46 UTC, owenca commented on buzzwindow.cpp
> +	TimeElapsed->SetFontSize(22);
This only works with the 12-point font size. We will live with it for now, but can you please create a new issue for this?

2020-01-10 01:46 UTC, owenca commented on buzzwindow.cpp
> +			.AddGroup(B_HORIZONTAL, 1)
Can you use an appropriate `B_...` macro for the spacing value instead?

2020-01-10 02:30 UTC, Ra-V2 commented
I added AddGlue() because when we drop a file with small amount of characters name, the test button and file name get centered and this not looks good for me.

2020-01-10 04:34 UTC, owenca requested changes

2020-01-10 04:34 UTC, owenca commented on buzzwindow.cpp
> +	B_TITLED_WINDOW, B_NOT_RESIZABLE | B_NOT_ZOOMABLE | B_AUTO_UPDATE_SIZE_LIMITS)
```
	BWindow(BRect(30, 30, 0, 0), "WakeUp v1.0", B_TITLED_WINDOW,
		B_NOT_RESIZABLE | B_NOT_ZOOMABLE | B_AUTO_UPDATE_SIZE_LIMITS)
```

2020-01-10 04:34 UTC, owenca commented on buzzwindow.cpp
> +	IntervalControl = new BTextControl("", "", "5", NULL, B_WILL_DRAW);
IMO, the time value should be right aligned.

2020-01-10 04:34 UTC, owenca commented on buzzwindow.cpp
> +			.AddGroup(B_HORIZONTAL, B_TRACK_RECT_CORNER)
I suggest B_USE_HALF_ITEM_SPACING here.

2020-01-10 06:10 UTC, owenca requested changes
Can you update WakeUp.png and squash the commits? We can merge the PR after that.

Edit: Also make sure that ReadMe.md will show the new screenshot.

2020-01-10 07:16 UTC, owenca approved these changes

2020-01-10 07:46 UTC, merged